StreetlightControlCabinet:
  required:
    - id
    - type
    - location
    - refStreetlightGroup
    - workingMode
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: A Streetlight control cabinet
  properties:
    activePowerR:
      x-ngsi:
        type: Property
      type: number
      description: ''
    activePowerS:
      x-ngsi:
        type: Property
      type: number
      description: ''
    activePowerT:
      x-ngsi:
        type: Property
      type: number
      description: ''
    address:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/address
    alternateName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    annotations:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
    areaServed:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    brandName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    color:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    compliantWith:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
    cosPhi:
      x-ngsi:
        type: Property
      type: number
      description: ''
    cupboardMadeOf:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    dateLastProgramming:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    dateMeteringStarted:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    dateServiceStarted:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    energyConsumed:
      x-ngsi:
        type: Property
      type: number
      description: ''
    energyCost:
      x-ngsi:
        type: Property
      type: number
      description: ''
    features:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - astronomicalClock
          - individualControl
    frequency:
      x-ngsi:
        type: Property
      type: number
      description: ''
    image:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: ''
      format: uri
    intensityR:
      x-ngsi:
        type: Property
      type: number
      description: ''
    intensityS:
      x-ngsi:
        type: Property
      type: number
      description: ''
    intensityT:
      x-ngsi:
        type: Property
      type: number
      description: ''
    lastMeterReading:
      x-ngsi:
        type: Property
      type: number
      description: ''
    location:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/location
    manufacturerName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    maximumPowerAvailable:
      x-ngsi:
        type: Property
      type: number
      description: ''
    meterReadingPeriod:
      x-ngsi:
        type: Property
      type: number
      description: ''
    modelName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    nextActuationDeadline:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    owner:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items: &ref_0
        anyOf:
          - type: string
            minLength: 1
            maxLength: 256
            pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
          - type: string
            format: uri
    powerFactorR:
      x-ngsi:
        type: Property
      type: number
      description: ''
    powerFactorS:
      x-ngsi:
        type: Property
      type: number
      description: ''
    powerFactorT:
      x-ngsi:
        type: Property
      type: number
      description: ''
    reactiveEnergyConsumed:
      x-ngsi:
        type: Property
      type: number
      description: ''
    reactivePowerR:
      x-ngsi:
        type: Property
      type: number
      description: ''
    reactivePowerS:
      x-ngsi:
        type: Property
      type: number
      description: ''
    reactivePowerT:
      x-ngsi:
        type: Property
      type: number
      description: ''
    refDevice:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items: *ref_0
    refStreetlightGroup:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items: *ref_0
    responsible:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    serialNumber:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    source:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    thdrIntensityR:
      x-ngsi:
        type: Property
      type: number
      description: ''
    thdrIntensityS:
      x-ngsi:
        type: Property
      type: number
      description: ''
    thdrIntensityT:
      x-ngsi:
        type: Property
      type: number
      description: ''
    thdrVoltageR:
      x-ngsi:
        type: Property
      type: number
      description: ''
    thdrVoltageS:
      x-ngsi:
        type: Property
      type: number
      description: ''
    thdrVoltageT:
      x-ngsi:
        type: Property
      type: number
      description: ''
    totalActivePower:
      x-ngsi:
        type: Property
      type: number
      description: ''
    totalReactivePower:
      x-ngsi:
        type: Property
      type: number
      description: ''
    voltageR:
      x-ngsi:
        type: Property
      type: number
      description: ''
    voltageS:
      x-ngsi:
        type: Property
      type: number
      description: ''
    voltageT:
      x-ngsi:
        type: Property
      type: number
      description: ''
    workingMode:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
