Streetlight:
  required:
    - id
    - type
    - location
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: A Street light group
  properties:
    activeProgramId:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    address:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/address
    alternateName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    annotations:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
    areaServed:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    color:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    dateLastSwitchingOff:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    dateLastSwitchingOn:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    illuminanceLevel:
      x-ngsi:
        type: Property
      type: number
      description: ''
    image:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: ''
      format: uri
    location:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/location
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      x-ngsi:
        type: Relationship
        model: https://schema.org/URL  
      type: array
      description: ''
      items: &ref_0
        anyOf:
          - type: string
            minLength: 1
            maxLength: 256
            pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
          - type: string
            format: uri
    powerState:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    refStreetlight:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items: *ref_0
    source:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    switchingMode:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - night-ON
          - night-OFF
          - night-LOW
          - always-ON
          - day-ON
          - day-OFF
          - day-LOW
    switchingOnHours:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: object
        properties:
          from:
            type: string
            oneOf:
              - format: date
              - &ref_1
                type: string
                pattern: >-
                  ^--((0[13578]|1[02])-31|(0[1,3-9]|1[0-2])-30|(0\d|1[0-2])-([0-2]\d))$
          to:
            type: string
            oneOf:
              - format: date
              - *ref_1
          hours:
            type: string
          description:
            type: string
        required:
          - from
          - to
          - hours
