--- 
components: 
  schemas: 
    StreetlightGroup: 
      $ref: "https://smart-data-models.github.io/dataModel.Streetlighting/StreetlightGroup/model.yaml#/StreetlightGroup"
info: 
  description: |
    An entity of type StreetlightGroup represents a group of streetlights. They might be controlled together by the same automated system (cabinet controller).
  title: StreetlightGroup
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - StreetlightGroup
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Streetlighting/StreetlightGroup/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Streetlighting/StreetlightGroup/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
