--- 
components: 
  schemas: 
    Streetlight: 
      $ref: "https://smart-data-models.github.io/dataModel.Streetlighting/Streetlight/model.yaml#/Streetlight"
info: 
  description: |
    An entity of type Streetlight represents a urban streetlight. Actually, there will be an entity of type Streetlight per lamp. Thus, if a particular pole holds more than one lantern there will be as many streetlight entites as installed lamps. As a result there might be more than one streetlight entity per location. A Streetlight entity does not contain any attribute corresponding to structural characteristics. Such data is captured by entities of type StreetlightModel.

  title: Streetlight
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Streetlight
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Streetlighting/Streetlight/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Streetlighting/Streetlight/examples/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
